project_O/project_O/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls import handler404,handler500
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^vrlib/', TemplateView.as_view(template_name="vr.htm"), name='vr'),
    url(r'^virtual-tour/(?P<ssname>[-\w]+)/$','catalog.views.home.virtual_tour', name='virtual_tour'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT.replace('\\', '/')},name='media'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_PATH},name='static'),

    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^$', 'catalog.views.home.home', name="home"),


    url(r'^(?P<slug1>[-\w]+)/(?P<slug2>[-\w]+)/(?P<slug3>[-\w]+)/(?P<ssname>[-\w]+)',
        'catalog.views.home.third_screen', name='catalog_category'),

    url(r'^(?P<slug1>[-\w]+)/(?P<slug2>[-\w]+)/(?P<slug3>[-\w]+)/$',
        'catalog.views.home.second_screen', name='catalog_category'),

    url(r'^(?P<slug1>[-\w]+)/(?P<slug2>[-\w]+)/$',
        'catalog.views.home.second_screen', name='catalog_category'),

    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^vendor/', include('user_info.urls', namespace='user_info', app_name='UserInfo')),
    url(r'^faq/','catalog.views.footer.faq', name='faq'),
    url(r'^contact_us/','catalog.views.footer.contact_us', name='contact_us'),
    url(r'^about_us/','catalog.views.footer.about_us', name='about_us'),
    url(r'^terms-condition/','catalog.views.footer.terms', name='terms_condition'),
    # url(r'^vendor/del_sub_service', 'user_info.views.vendor_del_sub_service', name="del_sub_service"),


]
handler404 = 'catalog.views.home.handler404'
handler500 = 'catalog.views.home.handler500'

project_O/sales/urls.py
from django.conf.urls import include, url

from sales.views import add_to_cart, remove_from_cart, display_cart, get_quote

urlpatterns = [
    url(r'^add', add_to_cart, name='sales_add_to_cart'),
    url(r'^remove', remove_from_cart, name='remove_from_cart'),
    url(r'^cart', display_cart, name='display_cart'),
    url(r'^get_quote$', get_quote, name='get_quote'),
]

project_O/user_info/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^authenticate_vendor', 'user_info.views.authenticate_vendor', name='authenticate_vendor'),
    url(r'^login', 'user_info.views.login_vendor', name="vendor-login"),
    url(r'^logout', 'user_info.views.logout_vendor', name="vendor-logout"),
    url(r'^home', 'user_info.views.vendor_home', name="vendor-home"),
    url(r'^edit_sub_service/(?P<sub_service_id>[\w]+$)', 'user_info.views.edit_sub_service', name="edit-sub-service"),
    url(r'^edit_sub_service_update/(?P<sub_service_id>[\w]+$)', 'user_info.views.edit_sub_service_update',
        name="edit-sub-service-update"),
    url(r'^del_sub_service$', 'user_info.views.vendor_del_sub_service', name="del_sub_service"),
    url(r'^create_sub_service', 'user_info.views.create_sub_service', name="create-sub-service"),



]

project_O/templates/404error.html
{% extends "base.html" %}
{% block base_occasion_mob %}
    {% for occasion in occasions %}
        <li class="level1"> <a href="/occasion/{{ occasion.slug }}"> <span>{{ occasion.name }}</span> </a> </li>
    {% endfor %}
{% endblock %}

{% block base_outing_mob %}
    {% for outing in outings %}
        <li class="level1"><a href="/outing/{{ outing.slug }}"> <span>{{ outing.name }}</span></a></li>
    {% endfor %}
{% endblock %}

{% block base_offer_mob %}
          {% for offer in offers %}
          <li class="level1"><a href="/offer/{{ offer.slug }}"> <span>{{ offer.name }}</span></a></li>
          {% endfor %}
{% endblock %}

{% block base_occasion %}
    {% for occasion in occasions %}
        <li class="level1 nav-10-2"> <a href="/occasion/{{ occasion.slug }}"> <span>{{ occasion.name }}</span> </a> </li>
    {% endfor %}
{% endblock %}

{% block base_outing %}
    {% for outing in outings %}
        <li class="level1 first"><a href="/outing/{{ outing.slug }}"> <span>{{ outing.name }}</span></a></li>
    {% endfor %}
{% endblock %}

{% block base_offer %}
          {% for offer in offers %}
          <li class="level1 first"><a href="/offer/{{ offer.slug }}"> <span>{{ offer.name }}</span></a></li>
          {% endfor %}
{% endblock %}

{% block content %}
  <!-- end nav --> 
  <!-- main-container -->
  <section class="content-wrapper">
    <div class="container">
      <div class="std">
        <div class="page-not-found wow bounceInRight animated">
          <h3>Oops! The Page you requested was not found!</h3>
          <img src="{{STATIC_URL}}/images/coming-soon-1.png" alt="">
          <div><a href="/"  class="btn-home"><span>Back To Home</span></a></div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}
  <!--End main-container --> 

project_O/templates/about_us.html
{% extends "base.html" %}

{% block base_occasion_mob %}
    {% for occasion in occasions %}
        <li class="level1"> <a href="/occasion/{{ occasion.slug }}"> <span>{{ occasion.name }}</span> </a> </li>
    {% endfor %}
{% endblock %}

{% block base_outing_mob %}
    {% for outing in outings %}
        <li class="level1"><a href="/outing/{{ outing.slug }}"> <span>{{ outing.name }}</span></a></li>
    {% endfor %}
{% endblock %}

{% block base_offer_mob %}
          {% for offer in offers %}
          <li class="level1"><a href="/offer/{{ offer.slug }}"> <span>{{ offer.name }}</span></a></li>
          {% endfor %}
{% endblock %}

{% block base_occasion %}
    {% for occasion in occasions %}
        <li class="level1 nav-10-2"> <a href="/occasion/{{ occasion.slug }}"> <span>{{ occasion.name }}</span> </a> </li>
    {% endfor %}
{% endblock %}

{% block base_outing %}
    {% for outing in outings %}
        <li class="level1 first"><a href="/outing/{{ outing.slug }}"> <span>{{ outing.name }}</span></a></li>
    {% endfor %}
{% endblock %}

{% block base_offer %}
          {% for offer in offers %}
          <li class="level1 first"><a href="/offer/{{ offer.slug }}"> <span>{{ offer.name }}</span></a></li>
          {% endfor %}
{% endblock %}

{% block base_cart_sub_screens %}
{% include "cart.html" %}
{% endblock %}

{% block content %}
  <div class="breadcrumbs">
    <div class="container">
      <div class="row">
        <ul>
          <li class="home"> <a title="Go to Home Page" href="/">Home</a><span>&mdash;›</span></li>
          <li class="category13"><strong>About Us</strong></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- main-container -->
  <div class="main-container col2-right-layout">
    <div class="main container">
      <div class="row">
        <section class="col-main col-sm-9 wow bounceInUp animated">
          <div class="page-title">
            <h2>{{ heading }}</h2>
          </div>
          <div class="static-contain">
            {% for cname in content %}
            {{ cname.name | linebreaks }}
            {% endfor %}
          </div>
        </section>
        <aside class="col-right sidebar col-sm-3 wow bounceInUp animated">
          <div class="block block-company">
            <div class="block-title">Company </div>
            <div class="block-content">
              <ol id="recently-viewed-items">
                <li class="item odd"><a href="/about_us"><strong>About Us</strong></a></li>
                <!--<li class="item even"><a href="#">Privacy policy</a></li>-->
                <li class="item  odd"><a href="/terms-condition">Terms of Service</a></li>
                <!--<li class="item even"><a href="#">Search Terms</a></li>-->
                <li class="item last"><a href="/contact_us">Contact Us</a></li>
              </ol>
            </div>
          </div>
        </aside>
      </div>
    </div>
  </div>
  <!--End main-container -->
{% endblock content %}

project_O/templates/cart.html
{% block base_cart %}
{% with items=cart.get_items items_count=cart.get_items_count %}
        <div id="cart">
        <div data-toggle="dropdown" data-hover="dropdown" class="basket dropdown-toggle">
            <a href="sales/checkout">
                <div class="cart-box"><span id="cart-total"><strong>{{ items_count  }}</strong> item </span></div>
            </a>
        </div>
        <div>
            <div class="top-cart-content arrow_box">
                {% if items %}
                  <div class="block-subtitle">Recently added item(s)</div>
                  <ul id="cart-sidebar" class="mini-products-list">
                       {% for item in items %}
                        <li class="item last odd">
                          <a class="product-image" href="#" title="  {{ item.product.name }}  ">

                          <img alt="  {{ item.product.name }}  " src="{{ item.product.service_pic.all.0.image.url }}" width="80"></a>

                          <div class="detail-item">
                                <div class="product-details">

                                    <a  href="#" title="{{ item.product.name }}"
                                                              class="remove-cart glyphicon glyphicon-remove" value="{{ item.product.id }}">&nbsp;</a>
                                  <p class="product-name"><a title=" {{ item.product.name }} "> {{ item.product.name }} </a></p>
                              </div>

                              <div class="product-details-bottom">
                                  {% with price=item.pricing.final_amount disprice=item.pricing.get_discounted_price   %}
                                  {% if item.pricing.discount == 0.0 %}
                                  <span class="price">&#8377;{{ price }}</span>
                                  {% else %}
                                  <span class="price">&#8377;{{ disprice }}</span>
                                  {% endif %}
                                  {% endwith %}
                                  <span
                                      class="title-desc">Qty:</span> <strong>1</strong></div>

                          </div>
                      </li>
                    {% endfor %}

                  </ul>
                  <!--<div class="top-subtotal">Subtotal: <span class="price">&#8377;{{ cart.get_sub_total }}</span></div>-->
                  <div class="actions">
                    <button onclick="location.href = '{% url 'sales:display_cart' %}'" class="btn-checkout" type="button" ><span>Checkout</span></button>
                      <button onclick="location.href = '{% url 'sales:display_cart' %}'"  class="view-cart" type="button"><span>View Cart</span></button>
                  </div>
              </div>

                {% else %}
                <div class="block-subtitle">You have no items in your shopping cart.</div>

		        {% endif %}
            </div>
        </div>
        </div>
{% endwith %}
{% endblock %}

project_O/templates/vendor_create_offer.html
{% extends "vendor_base.html" %}
{% block welcome_vendor %}
    <span>Welcome {{ vendor_name }}</span>
{% endblock %}
{% block logout_vendor %}
    <span>Logout</span>
{% endblock %}
{% block content %}
  <!-- Two columns content -->
    <section class="main-container col2-left-layout">

        <div class="main container">
            <div class="row">
                <div class="col-main col-sm-9 col-sm-push-3 ">
                    <div class="category-title">
                        <h1>Create New</h1>
                    </div>
                    <div class="create_offers">
                        <div class="common-form">
                               <!--<form class="form-horizontal" role="form" id="create_offer">-->
                               <form id="create-offer">
                                      <fieldset class="group-select">

                                        <!-- Form Name -->
                                       <!-- Text input-->
                                        <div class="form-group input-box">
                                          <label class="col-sm-4 control-label" for="create_offer_name">Name</label>
                                          <div class="col-sm-8">
                                            <input type="text" placeholder="" id="create_offer_name" name="offer_name" class="input-text" required="">
                                          </div>
                                        </div>
                                        <!-- Text input-->
                                        <div class="form-group input-box">
                                          <label class="col-sm-4 control-label" for="create_offer">Offer</label>
                                          <div class="col-sm-8">
                                            <input type="text" placeholder="" id="create_offer" name="offer" class="input-text " required="">
                                          </div>
                                        </div>
                                          <!-- Text input-->
                                        <div class="form-group input-box">
                                          <label class="col-sm-4 control-label" for="create_min_bill">Discount (%) </label>
                                          <div class="col-sm-8">
                                            <input type="number" min="0"  max="100" placeholder="" id="create_min_bill" name="min_bill" class="input-text" required="">
                                          </div>
                                        </div>

                                       <!-- Text input-->
                                        <div class="form-group input-box">

                                          <label class="col-sm-4 control-label" for="create_fromdate">Duration</label>

                                             <div class="col-sm-8 ">
                                               <div class="row">
                                               <div class="col-sm-6">
                                                 <input type="text" id="create_fromdate" name="create_fromdate" class="input-text " placeholder="From" required="">
                                                </div>


                                                <div class="col-sm-6">
                                                   <input type="text" id="create_todate" name="create_todate" class="input-text " placeholder="To" required="">
                                                </div>
                                             </div>
                                           </div>
                                        </div>


                                           <!-- Text input-->
                                        <!--<div class="form-group input-box">-->
                                          <!--<label class="col-sm-4 control-label" for="offer_image">Insert Image</label>-->
                                          <!--<div class="col-sm-8">-->
                                            <!--<input type="file" class="input-text" id="offer_image" name="offer_image" accept="image/x-png, image/gif, image/jpeg, image/jpg">-->
                                          <!--</div>-->
                                        <!--</div>-->


                                        <!-- Text input-->
                                        <div class="form-group input-box">
                                          <label class="col-sm-4 control-label" for="create_desc">Text Message</label>
                                          <div class="col-sm-8">
                                            <textarea class="input-text" rows="3" name="desc" id="create_desc" placeholder="Your text goes here" required=""></textarea>
                                          </div>
                                        </div>



                                        <div class="form-group input-box btns-group clearfix">
                                          <div class="col-sm-offset-2 col-sm-10">
                                            <div class="pull-right">
                                              <button type="button" class="button submit" id="offer_cancel" onclick="window.location.reload()">Cancel</button>
                                              <button type="submit" class="button submit" id="save_offer" title="Submit">Save</button>
                                            </div>
                                          </div>
                                        </div>

                                      </fieldset>
                                    </form>
                              </div>
                    </div>
                </div>
                <aside class="col-left sidebar col-sm-3 col-xs-12 col-sm-pull-9 ">
                    <div class="side-nav-categories">
                        <div class="block-title">Offers Zone</div>
                        <div class="box-content box-category">
                            <ul id="magicat">
                                <li class="level0- level0 "> <span class="magicat-cat"><a href="{% url 'UserInfo:create-sub-service' %}"><span>Create</span></a>
                                    </span>
                                </li>
                                 <li class="level0- level0 "> <span class="magicat-cat"><a href="{% url 'UserInfo:vendor-home' %}"><span>View offers</span></a>
                                    </span>
                                </li>

                            </ul>
                        </div>
                    </div>

                </aside>
            </div>
        </div>
    </section>
    <!-- End Two columns content -->

{% endblock content %}

project_O/templates/vendor_offer_edit.html
{% extends "vendor_base.html" %}

{% block welcome_vendor %}
    <span>Welcome {{ vendor_name }}</span>
{% endblock %}

{% block logout_vendor %}
    <span>Logout</span>
{% endblock %}

{% block content %}
  <!-- Two columns content -->
    <section class="main-container col2-left-layout">

        <div class="main container">
            <div class="row">
                <div class="col-main col-sm-9 col-sm-push-3 ">
                    <div class="category-title">
                        <h1>Edit offer</h1>
                    </div>
                    <div class="create_offers">
                        <div class="common-form">
                               <form id="edit_sub_service">

                                      <fieldset class="group-select">
                                          <input id="edit_sub_service_id" type="hidden" value="{{id}}">
                                        <!-- Form Name -->
                                       <!-- Text input-->
                                        <div class="form-group input-box">
                                          <label class="col-sm-4 control-label" for="offer_name">Name</label>
                                          <div class="col-sm-8">
                                            <input type="text" placeholder="" id="offer_name" name="offer_name" class="input-text"  value="{{ name }}" required="">
                                          </div>
                                        </div>
                                        <!-- Text input-->
                                        <div class="form-group input-box">
                                          <label class="col-sm-4 control-label" for="offer">Offer</label>
                                          <div class="col-sm-8">
                                            <input type="text" placeholder="" id="offer" name="offer" class="input-text" value="{{ offer }}"  required="">
                                          </div>
                                        </div>
                                          <!-- Text input-->
                                        <div class="form-group input-box">
                                          <label class="col-sm-4 control-label" for="min_bill">Discount (%) </label>
                                          <div class="col-sm-8">
                                            <input type="number" min="0" max="100" placeholder="" id="min_bill" name="min_bill" class="input-text" value="{{ min_bill_amount }}" >
                                          </div>
                                        </div>

                                       <!-- Text input-->
                                        <div class="form-group input-box">

                                          <label class="col-sm-4 control-label" for="fromdate">Duration</label>

                                             <div class="col-sm-8 ">
                                               <div class="row">
                                               <div class="col-sm-6">
                                                 <input type="text" id="fromdate" name="fromdate" class="input-text " placeholder="" value="{{ from_duration }}" required="">
                                                </div>


                                                <div class="col-sm-6">
                                                   <input type="text" id="todate" name="todate" class="input-text " placeholder="" value="{{ to_duration }}" required="">
                                                </div>
                                             </div>
                                           </div>
                                        </div>

                                           <!-- Text input-->
                                        <!--<div class="form-group input-box">-->
                                          <!--<label class="col-sm-4 control-label" for="offer_image">Insert Image</label>-->
                                          <!--<div class="col-sm-8">-->
                                            <!--<input type="file" class="input-text" id="offer_image" name="offer_image" accept="image/x-png, image/gif, image/jpeg, image/jpg">-->
                                          <!--</div>-->
                                        <!--</div>-->


                                        <!-- Text input-->
                                        <div class="form-group input-box">
                                          <label class="col-sm-4 control-label" for="text_message">Text Message</label>
                                          <div class="col-sm-8">
                                            <textarea class="input-text" rows="3" name="text_message" id="text_message" placeholder="" required="" >{{ text_message }}</textarea>
                                          </div>
                                        </div>


                                        <div class="form-group input-box btns-group clearfix">
                                          <div class="col-sm-offset-2 col-sm-10">
                                            <div class="pull-right">

                                              <a href="{% url 'UserInfo:edit-sub-service' id %}" >
                                                  <button type="button" class="button submit">Reload</button>
                                              </a>
                                                <button type="submit" class="button submit" id="edit_offer" title="Submit">Update</button>
                                            </div>
                                          </div>
                                        </div>

                                      </fieldset>
                                    </form>
                              </div>
                    </div>
                </div>
                <aside class="col-left sidebar col-sm-3 col-xs-12 col-sm-pull-9 ">
                    <div class="side-nav-categories">
                        <div class="block-title">Offers Zone</div>
                        <div class="box-content box-category">
                            <ul id="magicat">
                                <li class="level0- level0 "> <span class="magicat-cat"><a href="{% url 'UserInfo:create-sub-service' %}"><span>Create</span></a>
                                    </span>
                                </li>
                                 <li class="level0- level0 "> <span class="magicat-cat"><a href="{% url 'UserInfo:vendor-home' %}"><span>View offers</span></a>
                                    </span>
                                </li>

                            </ul>
                        </div>
                    </div>

                </aside>
            </div>
        </div>
    </section>
    <!-- End Two columns content -->

{% endblock content %}

project_O/templates/vendor_view_offers.html
{% extends "vendor_base.html" %}

{% block welcome_vendor %}
    <span>Welcome {{ vendor_name }}</span>
{% endblock %}
{% block logout_vendor %}
    <span>Logout</span>
{% endblock %}

{% block content %}
  <!-- Two columns content -->
    <section class="main-container col2-left-layout">

        <div class="main container">
            <div class="row">
                <div class="col-main col-sm-9 col-sm-push-3 ">
                    <div class="category-title">
                        <h1>Offers List</h1>
                    </div>
                    <div class="category-products">
                        <ul class="products-grid row" >
                            {% for sub_service in sub_services %}
                                <li class="item col-lg-4 col-md-3 col-sm-4 col-xs-12">
                                <div class="col-item">
                                    {% if sub_service.status == 'Active' %}
                                        <div class="new-label new-top-left">{{ sub_service.status }}</div>
                                    {% else %}
                                        <div style="width: 82px" class="sale-label new-top-left">{{ sub_service.status }}</div>
                                    {% endif %}
                                    <div class="product-image-area">
                                        <a class="product-image" title="{{ sub_service.name }}" href="#"> <img src="{{ sub_service.image }}" class="img-responsive" alt="o4u" /> </a>
                                    </div>

                                    <div class="info">
                                        <div class="info-inner">
                                            <div class="item-title"><a title="{{ sub_service.name }}" href="#">{{ sub_service.name }}</a></div>
                                            <!--itfem-title-->
                                            <div class="item-content">
                                                <div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating"></div>
                                                    </div>
                                                </div>
                                                {% if sub_service.price|length == 0 %}
                                                <div class="price-box"><span class="regular-price"> <span class="price">Contact for price</span> </span></div>
                                                    {% else %}
                                                <div class="price-box"><span class="regular-price"> <span class="pricepretext">{{ sub_service.price.0.displayprice.0|safe }}</span><span class="price">{{ sub_service.price.0.displayprice.1 }}</span><span class="priceposttext">{{ sub_service.price.0.displayprice.2 }}</span></span></div>

                                                {% endif %}
                                            </div>
                                            <!--item-content-->
                                        </div>
                                        <!--info-inner-->
                                        <div class="actions">

                                            <a href="{% url 'UserInfo:edit-sub-service' sub_service.id %}" ><button type="button" id="edit_ss"  title="Edit" class="button btn-cart" value="{{ sub_service.id }}" >
                                                <span>Edit</span>
                                            </button></a>

                                            <button type="button" id="delete_ss"  title="Delete" class="button btn-cart" value="{{ sub_service.id }}" onclick="delete_sub_service({{ sub_service.id }})">
                                                <span>Delete</span>
                                            </button>
                                        </div>
                                        <!--actions-->
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                                </li>
                            {% endfor %}

                            <input type="hidden" id="current_page" data-page="{{page}}" data-sort="{{sort}}">
                        </ul>
                        <br>

                            <div class="text-center">
                             <a  href="#" class="viewmore button " style="display: inline-block; width: 100%;" data-page="{{page}}" data-sort="{{sort}}"><b><span>VIEW MORE</span></b></a>
                           </div>
                    </div>
                </div>
                <aside class="col-left sidebar col-sm-3 col-xs-12 col-sm-pull-9 ">
                    <div class="side-nav-categories">
                        <div class="block-title"> Categories</div>
                        <div class="box-content box-category">
                             <ul id="magicat">
                                <li class="level0- level0 "> <span class="magicat-cat"><a href="{% url 'UserInfo:create-sub-service' %}"><span>Create</span></a>
                                    </span>
                                </li>
                                 <li class="level0- level0 "> <span class="magicat-cat"><a href="{% url 'UserInfo:vendor-home' %}"><span>View offers</span></a>
                                    </span>
                                </li>

                            </ul>
                        </div>
                    </div>

                </aside>
            </div>
        </div>
    </section>
    <!-- End Two columns content -->

{% endblock content %}